{{- $configMap := toYaml .Values.mrAutocloserConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-mr-autocloser.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    ---
{{ tpl $configMap . | indent 4 }}
