apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-mr-autocloser.fullname" . }}
  labels:
    {{- include "gitlab-mr-autocloser.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gitlab-mr-autocloser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitlab-mr-autocloser.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitlab-mr-autocloser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: health
              containerPort: {{ .Values.mrAutocloserConfig.healthcheckOptions.port }}
              protocol: TCP
          command: [ "./mr-autocloser" ]
          args: ["-config=./config/config.yaml"]
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
            httpGet:
              path: {{ .Values.mrAutocloserConfig.healthcheckOptions.liveness.path }}
              port: health
              scheme: HTTP
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
            httpGet:
              path: {{ .Values.mrAutocloserConfig.healthcheckOptions.readiness.path }}
              port: health
              scheme: HTTP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GITLAB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "gitlab-mr-autocloser.fullname" . }}
                  key: GITLAB_API_TOKEN
                  optional: false
          volumeMounts:
            - name: config-volume
              mountPath: /go/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "gitlab-mr-autocloser.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
