{{- if .Values.secrets.defaultSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-mr-autocloser.fullname" . }}
  labels:
{{- include "gitlab-mr-autocloser.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}