{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gitlab-mr-autocloser.fullname" . }}
  labels:
  {{- include "gitlab-mr-autocloser.labels" . | nindent 4 }}
  {{- toYaml .Values.serviceMonitor.promOperatorSelector | nindent 4 }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - path: {{ .Values.serviceMonitor.path }}
    port:  {{ .Values.serviceMonitor.port | squote }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- with .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector:
    matchLabels:
      {{- include "gitlab-mr-autocloser.labels" . | nindent 6 }}
{{- end }}