---
# Cron expressions.
cronSchedule: "*/1 * * * *"
# The head of MR label: "staleMR::closeAfterDays::<closeMRAfterDays>"
labelHead: "close_if_no_updates_days::"
# Gitlab Base API URL
gitlabBaseApiUrl: "https://gitlab.com/api/v4"

# http/net healthcheck options
healthcheckOptions:
  # Application binding host.
  host: 127.0.0.1
  # Application port for exposing liveness and readiness probes.
  port: 8090
  liveness:
    path: "/healthz/live"
    # goroutineHealthcheckHandler check fails if too many goroutines are running.
    gorMaxNum: 100
  readiness:
    path: "/healthz/ready"
    # dnsHealthcheckHandler returns a Check that makes sure the provided host can resolve to at least one IP address within the specified timeout.
    resolveTimeoutSec: 5
    urlCheck: "gitlab.com"

defaultOptions:
  # All opened MRs will be labeled as stale after staleMRAfterDays since CREATION DATE TIME.
  staleMRAfterDays: 14
  # Close stale opened MRs after closeMRAfterDays since LAST UPDATED TIME.
  closeMRAfterDays: 7

projects:
  - name: "contact-center/integrations/devops/environments/engage-voice/test-pipeline"
    # you can override defaults
#    overrideOptions:
#      staleMRAfterDays: 1
#      closeMRAfterDays: 5
  - name: "contact-center/integrations/devops/environments/engage-voice/test-pipeline2"
    # you can override defaults
#    overrideOptions:
#      staleMRAfterDays: 1
#      closeMRAfterDays: 5
  - name: "contact-center/integrations/devops/environments/engage-voice/test-pipeline3"
    # you can override defaults
#    overrideOptions:
#      staleMRAfterDays: 1
#      closeMRAfterDays: 5